remote: true
hybrid: true
onsite: true

experience_level:
  internship: true
  entry: false
  associate: false
  mid_senior_level: false
  director: false
  executive: false

job_types:
  full_time: true
  contract: true
  part_time: true
  temporary: true
  internship: true
  other: true
  volunteer: false

date:
  all_time: false
  month: false
  week: true
  24_hours: true

positions:
  - Software Intern

locations:
  - United States
  - San Francisco
  - New York City
  - Seattle
  - Austin
  - Boston
  - Los Angeles
  - Chicago
  - Denver
  - Raleigh
  - Atlanta
  - Florida
  - Miami

apply_once_at_company: true

distance: 100

company_blacklist:

title_blacklist:
  - freelance

location_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 500

# llm_model_type: ollama
llm_model: 'llama3.2:latest'
llm_api_url: 'http://127.0.0.1:11434/'
