remote: true
hybrid: true
onsite: true

experience_level:
  internship: true
  entry: false
  associate: false
  mid_senior_level: false
  director: false
  executive: false

job_types:
  full_time: true
  contract: true
  part_time: true
  internship: true


date:
  all_time: false
  month: false
  week: true
  24_hours: true

position: 'Software Intern'

locations:
  - '102571732' # New York, New York
  - '103644278' # United States

apply_once_at_company: true

distance: 100

company_blacklist:

title_blacklist:
  - freelance

location_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 500

# llm_model_type: ollama
llm_model: 'llama3.2:latest'
llm_api_url: 'http://127.0.0.1:11434/'
